### ISSUE TITLE
External kms server is fully safe?

### ISSUE THREAD

**Issue by japiotr123** [nakorndev/windows-ten-chan#1]
Hello
External kms server is fully safe?

**Comment by nakorndev** [comment]
Not fully safe fore sure if compare with buy a right license.

Support Microsoft and get fully safe with online feature or use pirate way to risk of your PC is up to you like other crack. No any methods are safe 100% for crack.

**Comment by japiotr123** [comment]
Sorry I misspelled the question
By KMS server cannot be sended any viruses?

**Comment by nakorndev** [comment]
Should be not (but still unsure)

To explain KMS method is like we using a PC on some organization that contains many licenses for Windows to give permission use as an employee.

Which I don't have much idea about they can be managed some on your PC or not? like spy or keep send some data on your PC. Think a KMS provider is like our boss at work.

The main problem is not about virus that should destroy your devices, but it's all about private things. If you don't care much that data on your PC such as you just play a games or fun with internet, so it should be worth to risk.

But if you use for development a things, jobs to do, transactions of any currency like crypto or else that should be a bit risk. But just "A BIT RISK" since I didn't notice any kind of this problem before. I think around 70% of all PC in the world using this way to crack a Windows.

As I said before to prevent those problem and keep 100% safe you should buy a right one at Microsoft. 🎉

See more at https://en.wikipedia.org/wiki/Volume_licensing
